name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev automake libltdl-dev
          pip install buildozer==1.5.0 cython==0.29.33 python-for-android==2023.9.16

      - name: Prepare NDK and sounds folder
        run: |
          mkdir -p ~/.buildozer/android/platform
          mkdir -p sounds
          mv *.mp3 *.wav sounds/ 2>/dev/null || true
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip -d ~/.buildozer/android/platform/
          python3 -c "
          import re
          f = open('/home/runner/.local/lib/python3.10/site-packages/buildozer/targets/android.py')
          c = f.read()
          f.close()
          c = c.replace(\"DEFAULT_ANDROID_NDK_VERSION = '17c'\", \"DEFAULT_ANDROID_NDK_VERSION = '25b'\")
          f = open('/home/runner/.local/lib/python3.10/site-packages/buildozer/targets/android.py', 'w')
          f.write(c)
          f.close()
          print('NDK parcheado a r25b')
          "

      - name: Build APK
        env:
          ANDROIDNDK: /home/runner/.buildozer/android/platform/android-ndk-r25b
          ANDROIDAPI: "33"
        run: |
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Hidratacion-v1.4
          path: bin/*.apk
